name: CI

on:
    push:
        branches:
            - '**'
        tags-ignore:
            - '*.*'
        paths-ignore:
            - README.md

jobs:
    test-web:
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
            - uses: actions/checkout@v2
            - name: Restore Dependency Cache
              uses: actions/cache@v1
              with:
                  path: ~/.npm
                  key: ${{ runner.OS }}-dependency-cache-${{ hashFiles('**/package.json') }}
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
#    test-ios:
#        runs-on: macos-latest
#        timeout-minutes: 30
#        strategy:
#            matrix:
#                xcode:
#                    - /Applications/Xcode_12.4.app
#        steps:
#            - run: sudo xcode-select --switch ${{ matrix.xcode }}
#            - uses: actions/setup-node@v1
#              with:
#                  node-version: 14.x
#            - uses: actions/checkout@v2
#            - name: Restore Dependency Cache
#              uses: actions/cache@v1
#              with:
#                  path: ~/.npm
#                  key: ${{ runner.OS }}-dependency-cache-${{ hashFiles('**/package.json') }}
#            - run: npm install
#            - run: npm run verify
#              working-directory: ./ios
#    test-android:
#        runs-on: ubuntu-latest
#        timeout-minutes: 30
#        steps:
#            - name: Checkout latest source
#              uses: actions/checkout@v2
#
#            - name: Set up JDK 11
#              uses: actions/setup-java@v1
#              with:
#                  java-version: 11
#
#            - name: Set up Node
#              uses: actions/setup-node@v2
#              with:
#                    node-version: 16
#
#            - name: Grant execute permission for gradlew
#              run: chmod +x gradlew
#              working-directory: ./android
#
#            - name: Cache .gradle
#              uses: actions/cache@v1
#              with:
#                  path: .gradle
#                  key: ${{ runner.os }}-dotgradle-${{ hashFiles('**/build.gradle') }}
#                  restore-keys: |
#                      ${{ runner.os }}-dotgradle-
#
#            - name: Cache gradle
#              uses: actions/cache@v1
#              with:
#                  path: ~/.gradle
#                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
#                  restore-keys: |
#                      ${{ runner.os }}-gradle-
#
#            - name: Install Capacitor Android dependency
#              run: npm ci
#
#            - name: Run Tests
#              run: ./gradlew test
#              working-directory: ./android
